services:
  postgres:
    image: postgres:${POSTGRES_VERSION:-16}
    environment:
      # use generic postgres env vars to configure env vars specific to dockerized postgres
      POSTGRES_DB: ${PGDATABASE:-portaldb}
      POSTGRES_PASSWORD: ${PGPASSWORD:-wplatrop}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d portaldb"]
      interval: 5s
      retries: 3
      start_period: 10s
      timeout: 5s
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - "./custom/db:/docker-entrypoint-initdb.d"
    ports:
      # only listen on localhost
      - "127.0.0.1:5432:5432"

  prodanon:
    build: ./prodanon
    environment:
      # use generic postgres env vars to configure env vars specific to dockerized postgres
      POSTGRES_HOST: postgres
      POSTGRES_DB: ${PGDATABASE:-portaldb}
      POSTGRES_PASSWORD: ${PGPASSWORD:-wplatrop}
    depends_on:
      postgres:
        condition: service_healthy

volumes:
    postgres-data: {}
