services:
  db_target:
    # separate postgres db to silo anon work from production
    image: postgres:${POSTGRES_VERSION:-16}
    environment:
      POSTGRES_DB: ${PGDATABASE:-anonportaldb}
      POSTGRES_PASSWORD: ${PGPASSWORD:-targetdbpass}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d anonportaldb"]
      interval: 5s
      retries: 3
      start_period: 10s
      timeout: 5s
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - /backups/truenth-portal/:/tmp/backups:ro
        #- "./prodanon/custom/db:/docker-entrypoint-initdb.d"
    ports:
      # only listen on localhost
      - "127.0.0.1:5432:5432"

  prodanon:
    build: ./prodanon
    environment:
      # use generic postgres env vars to configure env vars specific to dockerized postgres
      POSTGRES_HOST: db_target
      POSTGRES_USER: postgres
      POSTGRES_DB: ${PGDATABASE:-anonportaldb}
      POSTGRES_PASSWORD: ${PGPASSWORD:-targetdbpass}
    depends_on:
      db_target:
        condition: service_healthy

volumes:
    postgres-data: {}
