services:
  redis:
    image: redis
    ports:
      # only listen on localhost
      - "127.0.0.1:6379:6379"

  postgres:
    image: postgres:${POSTGRES_VERSION:-13}
    environment:
      # use generic postgres env vars to configure env vars specific to dockerized postgres
      POSTGRES_DB: ${PGDATABASE:-portaldb}
      POSTGRES_PASSWORD: ${PGPASSWORD:-wplatrop}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - "./config/db:/docker-entrypoint-initdb.d"
    ports:
      # only listen on localhost
      - "127.0.0.1:5432:5432"

volumes:
    postgres-data: {}
